run:
  #modules-download-mode: readonly
linters-settings:
  govet:
    check-shadowing: false
  golint:
    min-confidence: 0
  gocognit:
    min-complexity: 30
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  depguard:
    list-type: whitelist
    packages:
      - github.com/beorn7/perks/quantile
      - github.com/golang/glog
      - github.com/golang/protobuf/proto
      - github.com/nikandfor/cli
      - github.com/nikandfor/errors
      - github.com/nikandfor/json
      - github.com/nikandfor/tlog
      - github.com/nikandfor/xrain
      - github.com/nikandfor/goid
      - github.com/stretchr/testify/assert
      - github.com/stretchr/testify/require
      - google.golang.org/protobuf
  misspell:
  lll:
    line-length: 170
  goimports:
    local-prefixes: github.com/nikandfor/tlog
  prealloc:
    simple: true
    for-loops: true
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - unnamedResult
      - builtinShadow
      - commentedOutCode
      - appendAssign
      - whyNoLint
      - yodaStyleExpr

linters:
  enable-all: true
  disable:
    - unparam
    - nakedret
    - gochecknoinits
    - gochecknoglobals
    - prealloc
    - gomnd
    - testpackage
    - nlreturn
    - funlen
    - godox
    - gci
    - wsl
    - goerr113
