run:
  #modules-download-mode: readonly
linters-settings:
  govet:
    check-shadowing: false
  golint:
    min-confidence: 0
  gocognit:
    min-complexity: 30
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  depguard:
    list-type: whitelist
    packages:
      - github.com/beorn7/perks/quantile
      - github.com/gin-gonic/gin
      - github.com/golang/glog
      - github.com/golang/protobuf/proto
      - github.com/nikandfor/cli
      - github.com/nikandfor/errors
      - github.com/nikandfor/goid
      - github.com/nikandfor/json
      - github.com/nikandfor/quantile
      - github.com/nikandfor/tlog
      - github.com/nikandfor/xrain
      - github.com/opentracing/opentracing-go
      - github.com/prometheus/client_golang
      - github.com/prometheus/client_model
      - github.com/sirupsen/logrus
      - github.com/stretchr/testify/assert
      - github.com/stretchr/testify/require
      - github.com/uber/jaeger-client-go
      - google.golang.org/protobuf
      - go.opentelemetry.io/otel
      - go.uber.org/zap
  misspell:
  lll:
    line-length: 170
  goimports:
    local-prefixes: github.com/nikandfor/tlog
  prealloc:
    simple: true
    for-loops: true
  gocritic:
    enabled-tags:
      - experimental
      - performance
      - style
    disabled-checks:
      - appendAssign
      - builtinShadow
      - commentedOutCode
      - unnamedResult
      - whyNoLint
      - yodaStyleExpr

linters:
  enable-all: true
  disable:
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - godox
    - goerr113
    - gomnd
    - nakedret
    - nlreturn
    - prealloc
    - testpackage
    - unparam
    - wsl
