language: go

env:
  - GO111MODULE=on

go:
  - "1.12"
  - "1.13"

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - test $TRAVIS_GO_VERSION = "1.13" && bash <(curl -s https://codecov.io/bash)
