language: go

env:
  - GO111MODULE=on

jobs:
  include:
    - os: linux
      go: "1.12"
      arch: amd64
      env:
        - GO111MODULE=on
        - CODECOV_UPLOAD=yes

    - os: linux
      go: "1.12"
      arch: arm64

    - os: linux
      go: "1.13"
      arch: amd64

    - os: linux
      go: "1.13"
      arch: arm64

    - os: osx
      go: "1.12"

    - os: osx
      go: "1.13"

    - os: windows
      go: "1.12"

    - os: windows
      go: "1.13"

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - test $CODECOV_UPLOAD = "yes" && bash <(curl -s https://codecov.io/bash)
